name: repo_viewer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2 # enables encryption and storage of access tokens on device
  webview_flutter: ^3.0.4 # Enables viewing of web pages within the app
  auto_route: ^4.2.1 # Helps implement Navigator 2.0
  material_design_icons_flutter: ^5.0.6996 # Icons submit by the material flutter community
  flash: ^2.0.3+3 # Better looking alert popups 
  material_floating_search_bar: ^0.3.7 # Better looking customizable search bar

  # ^ STATE MANAGEMENT PACKAGES
  flutter_hooks: ^0.18.0 # Simplifies stateful widgets
  hooks_riverpod: ^1.0.4 # Top class state management

  # ^ DATA CLASS MANAGEMENT PACKAGES
  freezed_annotation: ^2.1.0 # Mark data classes for building with freezed
  dartz: ^0.10.0-nullsafety.2 # provides 'either' type for proper error handling

  # ^ WEB OPERATION PACKAGES
  oauth2: ^2.0.0 # simplifies code for authentication with APIs
  dio: ^4.0.0 # a better http client
  json_annotation: ^4.6.0 # Goes with json_serializable 
  shimmer: ^2.0.0 # Shows shimmer effect when assets are loading from web

  # ^ LOCAL STORAGE PACKAGES
  sembast: ^3.2.0+1 # A great noSQL local storage solution
  path_provider: ^2.0.11 # Does the legwork of returning the local storage paths for both Android and IOS devices
  path: ^1.8.1 # provides common operations for manipulating paths: joining, splitting, normalizing, etc.
  cached_network_image: ^3.2.1 # Enables caching of network images to improve rebuilds


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4 # Builds the data classes when using freezed
  freezed: ^2.1.0+1 # Automates creation of robust data classes with best practice methods & operators
  auto_route_generator: ^4.2.0 # Generates the code for auto_route
  json_serializable: ^6.3.1 # Providers builders for handling JSON. Makes it easier to communicate between Data
  # classes and API's with respect to key > field matching
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

 
